spring:
  application:
    name: enrutaglp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: enrutaglp.123
    url: jdbc:mysql://localhost:3307/enrutaglp
    username: root
  flyway:    locations:    - classpath:/db/migration
